name: Java CI with Gradle

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Make directory for deliver
      run: mkdir deploy
      
    - name: Build with Gradle
      run: ./gradlew clean build
    
    - name: Copy jar
      run: cp ./build/libs/*.jar ./deploy/

    - name: Make zip file
      run: zip -r -qq ./$GITHUB_SHA.zip .

    # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
    - name: Congigure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
